require('./capped-mintable-token/all.test');
require('./erc1594/all.test');
require('./erc1644/all.test');
require('./cng1400/all.test');
require('./token-factory/all.test');
require('./token-repository/all.test');
require('./roles/all.test');
require('./atomic-swap/all.test');
require('./cng20/all.test');
